networks:
  lumen-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
        - "8080:80"
    volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - lumen-network
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
        - "4306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: homestead
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
        - lumen-network
  php:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: php
    volumes:
        - ./src:/var/www/html
    # command: php artisan migrate && php artisan db:seed && php artisan queue:work
    ports:
        - "5000:5000"
    depends_on:
        - composer
    networks:
        - lumen-network
  composer:
    image: composer
    command: composer install
    working_dir: /var/www/html
    volumes: 
        - ./src:/var/www/html
    networks:
        - lumen-network